apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dnj2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dnj2
    app.kubernetes.io/part-of: ci10t-786-0082-app
  name: devfile-sample-dnj2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dnj2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dnj2
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0082-tenant/ci10t-786-0082-app/devfile-sample-dnj2@sha256:658be5fde2a6af6591efb364b1e1533febf383816ddee3bb005533fd69150258
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
